### ISSUE TITLE
Error: release insipid-goat failed: serviceaccounts "storageoscluster-operator-sa" already exists

### ISSUE THREAD

**Issue by devilankur18** [storageos/charts#20]
I have install storageos yesterday only, it seems storageos-operator has came in today. Not sure whats the difference. I am trying to resetup by deleting the storage os

```
$ helm delete storageos 
```

And installing 
```
$ helm install storageos/storageoscluster-operator --namespace storageos-operator
```

it gives error 
```
Error: release insipid-goat failed: serviceaccounts "storageoscluster-operator-sa" already exists
```

I tried deleting all  serviceaccounts, but this persist. Not sure how to fix this. Any suggestions ?

**Comment by darkowlzz** [comment]
Hi, sorry for the delay.
I'm unable to reproduce this, but I've seen similar stale resources due to which helm chart fails sometimes. Can you try the following and see if that helps?

Usually when `helm install` fails due to an existing resource, you can purge the failed chart deployment and that also removes any stale resources that caused the chart to fail.
```
$ helm delete --purge <deployment-name>
```

In this case, `storageoscluster-operator-sa` is the service account created in `storageos-operator` namespace. If helm deleting the deployment didn't work, you could delete the whole `storageos-operator` namespace to ensure that everything is deleted.

We perform this chart installation in our charts CI and we haven't seen such issue before https://travis-ci.org/storageos/charts/builds/458690203#L904.

Would be great if you could try this and see if it works.

Also, please update your helm repo with `helm repo update`. A new chart was released recently with new version of cluster-operator. And you can learn more about the cluster-operator from the project repo https://github.com/storageos/cluster-operator.

Hope this helps.

**Comment by croomes** [comment]
Closing old issue
